/**
 * GENERATED by scripts/sync-exit-config.mjs - DO NOT EDIT.
 * Source: onchain-config.json (network baseSepolia, deployed 2026-07-20T06:22:38.203Z).
 * Regenerate with: npm run sync:exit-config
 */

export const EXIT_CHAIN_ID = 84532 as const;
export const EXIT_NETWORK = "baseSepolia";
export const EXECUTOR_ADDRESS = "0xfaae2d3bdbAB24D645C71618eacCA7A3c81c65cf" as `0x${string}`;
export const LOCK_CHECKER_ADDRESS = "0x4518c4F6acC9ab3B3Ba5ED69c4Cd110AE55B8E85" as `0x${string}`;

export const EXIT_ADAPTERS = {
  aave: "0xC32BA88AbBb4DB914C928BC57A38C324c6A4c168" as `0x${string}`,
  moonwell: "0x6A7AC962a941442738Eeb132380BBb97a05be04E" as `0x${string}`,
  compound: "0x00210736e7E79640546D7E505097429E6A9816Ef" as `0x${string}`,
  morpho: "0x7211cb25746A21f375735c73d9E6f629EF710f41" as `0x${string}`,
} as const;

export const EXIT_USDC_ADDRESS = "0x036CbD53842c5426634e7929541eC2318f3dCF7e" as `0x${string}`;
export const EXIT_DATA_PROVIDER_ADDRESS = "0xBc9f5b7E248451CdD7cA54e717a2BFe1F32b566b" as `0x${string}`;
export const EXIT_WETH_ADDRESS = "0x4200000000000000000000000000000000000006" as `0x${string}`;

export const EXECUTOR_ABI = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "usdc_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "dataProvider_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "marketOracle_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "mockOracle_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "lockChecker_",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "aave",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "moonwell",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "compound",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "morpho",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "swap",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "uniswap",
            "type": "address"
          }
        ],
        "internalType": "struct PanikExecutor.AdapterAddresses",
        "name": "adapters_",
        "type": "tuple"
      },
      {
        "internalType": "address",
        "name": "nftManager_",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "address[]",
            "name": "assets",
            "type": "address[]"
          },
          {
            "internalType": "bytes[]",
            "name": "paths",
            "type": "bytes[]"
          },
          {
            "internalType": "uint16[]",
            "name": "minOutBps",
            "type": "uint16[]"
          }
        ],
        "internalType": "struct PanikExecutor.SwapConfigInput",
        "name": "swapConfig_",
        "type": "tuple"
      },
      {
        "internalType": "address[]",
        "name": "mockOracleAssets_",
        "type": "address[]"
      },
      {
        "internalType": "address[]",
        "name": "trackedAssets_",
        "type": "address[]"
      },
      {
        "internalType": "uint256",
        "name": "swapDeadlineBuffer_",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "CallerNotEOA",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "asset",
        "type": "address"
      }
    ],
    "name": "DuplicateAsset",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EmptyExit",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "asset",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "requiredAmount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "availableAmount",
        "type": "uint256"
      }
    ],
    "name": "InsufficientDebtAssetBalance",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "asset",
        "type": "address"
      },
      {
        "internalType": "uint16",
        "name": "minOutBps",
        "type": "uint16"
      }
    ],
    "name": "InvalidMinOutBps",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint8",
        "name": "decimals",
        "type": "uint8"
      }
    ],
    "name": "InvalidOracleDecimals",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "asset",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "attemptedAmount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "repaidAmount",
        "type": "uint256"
      }
    ],
    "name": "InvalidRepayAmount",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "asset",
        "type": "address"
      }
    ],
    "name": "InvalidTrackedAsset",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address[]",
        "name": "lockedAssets",
        "type": "address[]"
      }
    ],
    "name": "LockedPositions",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "asset",
        "type": "address"
      }
    ],
    "name": "MissingAToken",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "asset",
        "type": "address"
      }
    ],
    "name": "MissingSwapRoute",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "asset",
        "type": "address"
      }
    ],
    "name": "PriceUnavailable",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ReentrancyGuardReentrantCall",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "SafeERC20FailedOperation",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "usdcReceived",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "address[]",
        "name": "closed",
        "type": "address[]"
      },
      {
        "indexed": false,
        "internalType": "address[]",
        "name": "locked",
        "type": "address[]"
      }
    ],
    "name": "ExitCompleted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "enum ExitTypes.ProtocolId",
        "name": "protocol",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "asset",
        "type": "address"
      }
    ],
    "name": "LegClosed",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "AMOUNT_FULL",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "aaveAdapter",
    "outputs": [
      {
        "internalType": "contract AaveAdapter",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "enum ExitTypes.ProtocolId",
            "name": "protocol",
            "type": "uint8"
          },
          {
            "internalType": "address",
            "name": "asset",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "repayAmount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "withdrawAmount",
            "type": "uint256"
          },
          {
            "internalType": "bytes",
            "name": "data",
            "type": "bytes"
          }
        ],
        "internalType": "struct ExitTypes.ExitLeg[]",
        "name": "legs",
        "type": "tuple[]"
      },
      {
        "internalType": "uint256[]",
        "name": "uniswapTokenIds",
        "type": "uint256[]"
      }
    ],
    "name": "atomicExit",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "compoundAdapter",
    "outputs": [
      {
        "internalType": "contract CompoundV3Adapter",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "dataProvider",
    "outputs": [
      {
        "internalType": "contract IAaveProtocolDataProvider",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "asset",
        "type": "address"
      }
    ],
    "name": "getSwapConfig",
    "outputs": [
      {
        "internalType": "bool",
        "name": "enabled",
        "type": "bool"
      },
      {
        "internalType": "bytes",
        "name": "path",
        "type": "bytes"
      },
      {
        "internalType": "uint16",
        "name": "minOutBps",
        "type": "uint16"
      },
      {
        "internalType": "bool",
        "name": "useMockOracle",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "getTrackedAssets",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "lockChecker",
    "outputs": [
      {
        "internalType": "contract LockChecker",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "marketOracle",
    "outputs": [
      {
        "internalType": "contract IAssetOracle",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "mockOracle",
    "outputs": [
      {
        "internalType": "contract IAssetOracle",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "moonwellAdapter",
    "outputs": [
      {
        "internalType": "contract MoonwellAdapter",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "morphoAdapter",
    "outputs": [
      {
        "internalType": "contract MorphoAdapter",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "nftManager",
    "outputs": [
      {
        "internalType": "contract INonfungiblePositionManager",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "swapAdapter",
    "outputs": [
      {
        "internalType": "contract SwapAdapter",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "swapDeadlineBuffer",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "uniswapAdapter",
    "outputs": [
      {
        "internalType": "contract UniswapAdapter",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "usdc",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

export const LOCK_CHECKER_ABI = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "dataProvider_",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "stableDebtCooldownSeconds_",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "dataProvider",
    "outputs": [
      {
        "internalType": "contract IAaveProtocolDataProvider",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "asset",
        "type": "address"
      }
    ],
    "name": "getLockStatus",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bool",
            "name": "stableDebtCooldown",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "frozenReserve",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "zeroLiquidityReserve",
            "type": "bool"
          }
        ],
        "internalType": "struct LockChecker.LockStatus",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "internalType": "address[]",
        "name": "assets",
        "type": "address[]"
      }
    ],
    "name": "getLockedAssets",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "locked",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "user",
        "type": "address"
      },
      {
        "components": [
          {
            "internalType": "enum ExitTypes.ProtocolId",
            "name": "protocol",
            "type": "uint8"
          },
          {
            "internalType": "address",
            "name": "asset",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "repayAmount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "withdrawAmount",
            "type": "uint256"
          },
          {
            "internalType": "bytes",
            "name": "data",
            "type": "bytes"
          }
        ],
        "internalType": "struct ExitTypes.ExitLeg[]",
        "name": "legs",
        "type": "tuple[]"
      }
    ],
    "name": "getLockedLegs",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "locked",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "stableDebtCooldownSeconds",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
